import React, { useState } from "react";
import { Proposal } from "../types";
import { 
  Sparkles, 
  Layers, 
  MapPin, 
  DollarSign, 
  TrendingUp, 
  ArrowUpRight,
  Calculator,
  Loader2,
  Calendar,
  AlertCircle,
  FileCheck2,
  Plus
} from "lucide-react";

interface EstimatorProps {
  proposals: Proposal[];
  onAddProposal: (prop: Proposal) => void;
}

export const EstimatorView: React.FC<EstimatorProps> = ({
  proposals,
  onAddProposal
}) => {
  // AI Estimator input states
  const [estProjName, setEstProjName] = useState("");
  const [estType, setEstType] = useState("Home Renovation");
  const [estSqft, setEstSqft] = useState("2000");
  const [estLoc, setEstLoc] = useState("San Francisco, CA");
  const [estBudgetLimit, setEstBudgetLimit] = useState("");
  const [estSow, setEstSow] = useState("");

  const [loading, setLoading] = useState(false);
  const [aiReport, setAiReport] = useState<any | null>(null);
  const [errorMessage, setErrorMessage] = useState("");

  // Stats computation
  const totalPipeline = proposals.reduce((sum, p) => sum + p.value, 0);
  const totalApproved = proposals.filter(p => p.status === "Approved").length;
  const totalSent = proposals.filter(p => p.status === "Sent").length;

  const handleRunAiEstimator = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!estProjName || !estSqft) {
      setErrorMessage("Please supply a valid Project Name and size in Sq Ft.");
      return;
    }

    setLoading(true);
    setErrorMessage("");
    setAiReport(null);

    try {
      const response = await fetch("/api/estimate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          projectName: estProjName,
          projectType: estType,
          sqft: Number(estSqft),
          location: estLoc,
          budgetConstraint: estBudgetLimit ? Number(estBudgetLimit) : null,
          description: estSow
        }),
      });

      const json = await response.json();
      if (json.success) {
        setAiReport(json.data);
      } else {
        setErrorMessage(json.error || "Estimation request faulted inside backend routing.");
      }
    } catch (err: any) {
      console.error(err);
      setErrorMessage("Network connection to AI Estimator service timed out. Please verify local port bindings.");
    } finally {
      setLoading(false);
    }
  };

  const handleApplyAiProposal = () => {
    if (!aiReport) return;

    const created: Proposal = {
      id: "prop_" + Date.now(),
      projectName: estProjName,
      clientName: "AI Lead (" + (estLoc.split(",")[0] || "Local") + ")",
      value: aiReport.estimatedTotalBudget,
      status: "Approved",
      dateSent: "Today, AI Estimated",
      notes: `Generated by Contractor Pro AI. SOW: ${estSqft} sqft ${estType}. ${aiReport.aiTips?.[0] || ""}`
    };

    onAddProposal(created);
    alert(`AI Estimated proposal successfully compiled and appended to bid pipelines! Check the list below.`);
    
    // Clear Report
    setAiReport(null);
    setEstProjName("");
    setEstSqft("2000");
    setEstSow("");
    setEstBudgetLimit("");
  };

  return (
    <div id="ai-estimator-view" className="space-y-6">
      
      {/* Overview Stats Bento Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 bg-slate-900/60 rounded-xl border border-slate-800">
          <span className="text-[10px] text-slate-400 font-mono uppercase tracking-wider block">Gross Bid Pipeline SOW</span>
          <div className="text-2xl font-bold font-display text-cyan-400 mt-1">${totalPipeline.toLocaleString()}</div>
          <p className="text-[10px] text-slate-400 mt-1">Sum value of all bidding drafts</p>
        </div>

        <div className="p-4 bg-slate-900/60 rounded-xl border border-slate-800">
          <span className="text-[10px] text-slate-400 font-mono uppercase tracking-wider block">Proposals Authorized</span>
          <div className="text-2xl font-bold font-display text-emerald-400 mt-1">{totalApproved} Approved</div>
          <p className="text-[10px] text-slate-450 mt-1">Ready for contract excavation</p>
        </div>

        <div className="p-4 bg-slate-900/60 rounded-xl border border-slate-800">
          <span className="text-[10px] text-slate-400 font-mono uppercase tracking-wider block">Awaiting Owner Reply</span>
          <div className="text-2xl font-bold font-display text-amber-500 mt-1">{totalSent} Bids Sent</div>
          <p className="text-[10px] text-slate-455 mt-1">Follow up sequence loaded</p>
        </div>

        <div className="p-4 bg-cyan-950/20 rounded-xl border border-cyan-500/10 flex items-center gap-3">
          <Sparkles className="w-8 h-8 text-cyan-400 animate-pulse flex-shrink-0" />
          <div>
            <h4 className="text-xs font-bold text-white font-display">Contractor Pro AI Estimator</h4>
            <p className="text-[10px] text-cyan-400 leading-snug font-mono mt-0.5">Dual-mode server cost analyzer active</p>
          </div>
        </div>
      </div>

      {/* Main Grid: AI Estimator parameters console versus Current Proposals */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column: Estimator Console (7 cols) */}
        <div className="lg:col-span-7 space-y-4">
          <div className="bg-slate-900/60 p-5 rounded-2xl border border-slate-800 space-y-4">
            <div className="flex items-center gap-2">
              <Calculator className="w-5 h-5 text-cyan-400" />
              <h2 className="text-lg font-bold font-display text-white">Neural Construction Cost Estimator</h2>
            </div>
            <p className="text-xs text-slate-405">
              Submit dimensions & specifications. The estimation engine parses trades, raw regional supplies, permit codes, and computes budgets.
            </p>

            <form onSubmit={handleRunAiEstimator} className="grid grid-cols-2 gap-4 text-xs">
              <div className="col-span-2">
                <label className="block text-slate-400 font-mono mb-1">Project Name / Build Location Label *</label>
                <input
                  type="text"
                  required
                  value={estProjName}
                  onChange={(e) => setEstProjName(e.target.value)}
                  placeholder="e.g. Oak Ridge Custom Framing"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-white outline-none focus:border-cyan-500"
                />
              </div>

              <div>
                <label className="block text-slate-400 font-mono mb-1">Build Program Category</label>
                <select
                  value={estType}
                  onChange={(e) => setEstType(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-white outline-none focus:border-cyan-500"
                >
                  <option value="Home Renovation">Home Renovation</option>
                  <option value="Commercial Interior Buildout">Commercial Buildout</option>
                  <option value="Full Residential Frame">Residential Frame</option>
                  <option value="Multi-Family Decking">Multi-Family Decking</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-400 font-mono mb-1">Estimated Sq Footage *</label>
                <input
                  type="number"
                  required
                  value={estSqft}
                  onChange={(e) => setEstSqft(e.target.value)}
                  placeholder="e.g. 1800"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-white outline-none focus:border-cyan-500"
                />
              </div>

              <div>
                <label className="block text-slate-400 font-mono mb-1">Regional Location Zip/State</label>
                <input
                  type="text"
                  value={estLoc}
                  onChange={(e) => setEstLoc(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-white outline-none focus:border-cyan-500"
                />
              </div>

              <div>
                <label className="block text-slate-400 font-mono mb-1">Client target cost threshold ($)</label>
                <input
                  type="number"
                  value={estBudgetLimit}
                  onChange={(e) => setEstBudgetLimit(e.target.value)}
                  placeholder="e.g. 150000"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-white outline-none focus:border-cyan-500"
                />
              </div>

              <div className="col-span-2">
                <label className="block text-slate-400 font-mono mb-1">Description / Structural Specifications (SOW)</label>
                <textarea
                  rows={3}
                  value={estSow}
                  onChange={(e) => setEstSow(e.target.value)}
                  placeholder="e.g. Includes premium cedar cladding, open-truss design, thermal insulation pads, full HVAC ducts, double insulated windows."
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-white outline-none focus:border-cyan-500"
                />
              </div>

              <div className="col-span-2 pt-2">
                <button
                  type="submit"
                  disabled={loading}
                  className="w-full py-3 bg-gradient-to-r from-cyan-500 to-indigo-500 hover:opacity-90 active:scale-[0.99] text-slate-950 font-bold uppercase tracking-wider rounded-xl transition duration-200 flex items-center justify-center gap-2 glow-cyan cursor-pointer disabled:opacity-40"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin text-slate-950" />
                      Neural Network Calculating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4 text-slate-950" />
                      Run AI Estimation Engine
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>

          {/* AI Result Report Panel */}
          {aiReport && (
            <div className="bg-slate-950 border border-cyan-500/20 p-5 rounded-2xl space-y-4 glow-cyan text-xs">
              <div className="flex justify-between items-center pb-2 border-b border-slate-850">
                <div className="flex items-center gap-2">
                  <FileCheck2 className="w-5 h-5 text-cyan-400" />
                  <h3 className="font-bold text-white text-sm">AI Estimation Report Approved</h3>
                </div>
                <span className="text-[10px] bg-cyan-500/10 text-cyan-400 px-2 py-0.5 rounded font-mono font-bold uppercase">
                  Prediction S-Class
                </span>
              </div>

              {/* Total predicted budget layout */}
              <div className="bg-slate-900 p-4 rounded-xl flex justify-between items-center border border-slate-800/80">
                <div>
                  <span className="text-[10px] text-slate-450 font-mono uppercase tracking-wider block">Estimated Total Budget SOW</span>
                  <div className="text-3xl font-bold font-display text-cyan-400 mt-1">
                    ${aiReport.estimatedTotalBudget?.toLocaleString() || "Calculated"}
                  </div>
                </div>

                <button
                  onClick={handleApplyAiProposal}
                  className="px-4 py-2 bg-cyan-400 hover:bg-cyan-500 active:scale-95 text-slate-950 font-bold rounded-lg transition text-xs font-mono"
                >
                  Add to Bid Pipelines
                </button>
              </div>

              {/* Items cost breakdown */}
              <div className="space-y-3">
                <h4 className="font-semibold text-white font-mono uppercase text-[10px] tracking-wider text-slate-400">Budget Cost Allocation</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {aiReport.breakdown?.map((item: any, i: number) => (
                    <div key={i} className="p-2.5 rounded bg-slate-900 border border-slate-850 flex justify-between items-center">
                      <div>
                        <span className="text-[11px] font-medium text-white block truncate max-w-[150px]">{item.item}</span>
                        <span className="text-[10px] text-slate-450 font-mono tracking-wide">{item.percentage}% allocated</span>
                      </div>
                      <span className="text-cyan-405 font-bold font-mono">${item.cost?.toLocaleString()}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Sourced materials items */}
              <div className="space-y-3 pt-1">
                <h4 className="font-semibold text-white font-mono uppercase text-[10px] tracking-wider text-slate-400">Recommended Core Supplies</h4>
                <div className="bg-slate-900 rounded-lg overflow-hidden border border-slate-850">
                  <table className="w-full text-[11px] text-left">
                    <thead className="bg-slate-950 font-mono uppercase text-[9px] text-slate-450">
                      <tr>
                        <th className="p-2">Material / Supplies Description</th>
                        <th className="p-2">Suggested Quantity</th>
                        <th className="p-2 text-right">Value (EST)</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-850/60 font-mono">
                      {aiReport.materials?.map((mat: any, idx: number) => (
                        <tr key={idx} className="hover:bg-slate-850/30">
                          <td className="p-2 text-white font-sans">{mat.name}</td>
                          <td className="p-2 text-slate-400">{mat.quantity}</td>
                          <td className="p-2 text-right text-cyan-400">${mat.estimatedUnitCost?.toLocaleString()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Stage milestones */}
              <div className="space-y-3 pt-1">
                <h4 className="font-semibold text-white font-mono uppercase text-[10px] tracking-wider text-slate-400">Milestones sequence (Timeline schedule)</h4>
                <div className="space-y-2 border-l border-slate-800 pl-4 ml-2">
                  {aiReport.milestones?.map((phase: any, index: number) => (
                    <div key={index} className="relative">
                      <div className="absolute -left-[21px] top-1.5 w-2 h-2 rounded-full bg-cyan-400" />
                      <div className="text-[11px]">
                        <span className="font-semibold text-white">{phase.phase}</span>
                        <span className="text-slate-450 font-mono font-bold bg-slate-900 px-1.5 py-0.2 rounded ml-2">{phase.durationWeeks} Weeks</span>
                      </div>
                      <p className="text-[10px] text-slate-400 mt-0.5">{phase.deliverables?.join(", ")}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* SOW Tips */}
              <div className="p-3 bg-cyan-500/5 rounded-lg border border-cyan-500/10 space-y-1">
                <h5 className="font-bold text-cyan-400 uppercase font-mono text-[9px] tracking-wider">Estimated Tactical AI Tips</h5>
                <ul className="list-disc list-inside space-y-1 text-slate-350 text-[11px]">
                  {aiReport.aiTips?.map((tip: string, ti: number) => (
                    <li key={ti}>{tip}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          {errorMessage && (
            <div className="p-4 bg-rose-500/10 border border-rose-550/20 text-xs rounded-xl flex items-start gap-2.5">
              <AlertCircle className="w-4 h-4 text-rose-450 flex-shrink-0 mt-0.5" />
              <div>
                <strong className="text-rose-450 font-semibold text-white block">Connection Alert</strong>
                <p className="text-slate-400 mt-0.5">{errorMessage}</p>
              </div>
            </div>
          )}
        </div>

        {/* Right Column: Bidding Pipeline (5 cols) */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-slate-900/40 p-4 rounded-xl border border-slate-800 flex justify-between items-center">
            <h2 className="text-sm font-bold font-display text-white">Active General Proposals</h2>
            <span className="text-xs font-mono text-slate-450">({proposals.length} overall)</span>
          </div>

          <div className="space-y-3.5">
            {proposals.map((prop) => (
              <div key={prop.id} className="bg-slate-900/60 p-4 rounded-xl border border-slate-800 space-y-3 group hover:border-slate-700/80 transition">
                <div className="flex justify-between items-start gap-2">
                  <div>
                    <h3 className="font-semibold text-white leading-tight group-hover:text-cyan-400 transition">{prop.projectName}</h3>
                    <span className="text-[10px] text-slate-450 font-mono mt-1 block">Client: {prop.clientName} | {prop.dateSent}</span>
                  </div>
                  <span className={`px-2 py-0.5 rounded text-[9px] uppercase font-mono font-bold ${
                    prop.status === "Approved" 
                      ? "bg-emerald-450 text-slate-950" 
                      : prop.status === "Sent"
                      ? "bg-amber-400 text-slate-950"
                      : prop.status === "Drafting"
                      ? "bg-cyan-400 text-slate-950"
                      : "bg-slate-800 text-slate-400"
                  }`}>
                    {prop.status}
                  </span>
                </div>

                <p className="text-[11px] text-slate-400 line-clamp-2 leading-relaxed font-sans border-t border-slate-850/60 pt-2.5">
                  {prop.notes}
                </p>

                <div className="flex justify-between items-center text-xs font-mono text-slate-450">
                  <span>Gross SOW Sourcing Value</span>
                  <span className="text-white font-bold text-sm">${prop.value.toLocaleString()}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
};
