import os
from celery import Celery

BROKER = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
BACKEND = os.getenv("CELERY_RESULT_BACKEND", BROKER)

celery_app = Celery("contractor_pro", broker=BROKER, backend=BACKEND)
celery_app.conf.task_serializer = "json"
celery_app.conf.result_serializer = "json"
celery_app.conf.accept_content = ["json"]
celery_app.conf.timezone = "UTC"


@celery_app.task(name="tasks.generate_pdf_report")
def generate_pdf_report(project_id: str, tenant_id: str) -> dict:
    """Generate a PDF project report. CPU-bound — runs in worker process."""
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    import tempfile, os

    path = os.path.join("uploads", f"report_{project_id}.pdf")
    c = canvas.Canvas(path, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, 750, f"Project Report — {project_id}")
    c.setFont("Helvetica", 12)
    c.drawString(72, 720, "Generated by Contractor Pro")
    c.save()
    return {"fileUrl": f"/uploads/report_{project_id}.pdf"}


@celery_app.task(name="tasks.parse_dwg")
def parse_dwg(file_path: str) -> dict:
    """Parse a DWG/DXF file and return layer/entity summary. CPU-bound."""
    import ezdxf

    try:
        doc = ezdxf.readfile(file_path)
        msp = doc.modelspace()
        layers = [layer.dxf.name for layer in doc.layers]
        entity_count = len(list(msp))
        return {"layers": layers, "entityCount": entity_count}
    except Exception as e:
        return {"error": str(e)}
